### ISSUE TITLE
Better way to upload coverage data to codecov.io

### ISSUE THREAD

**Issue by jbrucker** [koakatta/demo-pyci#1]
https://github.com/koakatta/demo-pyci/blob/bae246455480d5b576be85c8965ec555d0dfe4b8/.github/workflows/Codecov.yml#L33-L35

What you used is the generic way, which you can even do from your own computer 
(if you add the Codecov token as an environment variable).
Github provides an Action so you don't need to download code from Codecov.
Just do this:
```
    - name: Upload coverage report using Github Action
      uses: codecov/codecov-action@v3
```
it is faster, too.

**Comment by koakatta** [comment]
edited the workflow
